image: node:latest

stages:
  - install
  - prettier
  - test

cache:
  paths:
    - node_modules

install:
  stage: install
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/

prettier:
  stage: prettier
  needs:
    - job: install
      artifacts: true
  script:
    - npm run prettier

test:unit:
  stage: test
  script:
    - npm run test:unit
