image: node:latest

stages:
  - install
  - prettier
  - test

cache:
  paths:
    - node_modules
    - .npm

install:
  stage: install
  script:
    - npm install

prettier:
  stage: prettier
  script:
    - npm run prettier

test:unit:
  stage: test
  script:
    - npm run test:unit
